#!/bin/sh
init_color=${init_color:-#FFFF00}
on_color=${on_color:-#00FF00}
name=$(basename $(ps --no-headers -fC openvpn | awk ' { for (i = 1; i <= NF; ++i) if ($i == "--config") print $(i+1); exit } '))
export init_color on_color name
nmcli -t connection show --active | awk -F ':' '
BEGIN {
    init_color=ENVIRON["init_color"]
    on_color=ENVIRON["on_color"]
}
$3=="vpn" {
    name=$1
    status="INIT"
    color=init_color
}
$3=="tun" || ($4~/^tap/ || $3~/^tap/) {
    name=ENVIRON["name"]
    status="ON"
    color=on_color
}
END {if(status) printf("%s\n%s\n%s\n", name, status, color)}'
