#!/bin/sh
off_color=${off_color:-#DE1212}
on_color=${on_color:-#00FF00}
export off_color on_color
nmcli -t connection show --active | awk -F ':' '
BEGIN {
  off_color=ENVIRON["off_color"]
  on_color=ENVIRON["on_color"]
}
$3=="vpn" {
  name=$1
  status="connected"
  color=on_color
}
END {
  if(status) {
    printf("%s\n%s\n%s\n", name, status, color)
  } else {
    printf("%s\n%s\n%s\n", "down", "down", off_color)
  }
}'
