#!/bin/bash

# Defaults


DISPLAY_RE="([0-9]+)x([0-9]+)\\+([0-9]+)\\+([0-9]+)"
IMAGE_RE="([0-9]+)x([0-9]+)"
FOLDER="$(dirname "$(readlink -f "$0")")"
LOCK="$FOLDER/lock.png"
TEXT="$FOLDER/text.png"
PARAMS=""
OUTPUT_IMAGE="/tmp/i3lock.png"
DISPLAY_TEXT=true
KEEP_PICTURE=false
BLURTYPE="1x1"
IMAGE_SOURCE_SCRIPT="$FOLDER/image_source.sh"

# Read user input
POSITIONAL=()
for i in "$@"
do
  case $i in
  -h|--help)
    echo "lock: Syntax: lock [-n|--no-text]"
    exit
    shift
    ;;
  -n|--no-text)
    DISPLAY_TEXT=false
    shift # past argument
    ;;
  *)    # unknown option
    echo "unknown option: $i"
    exit
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

_default_image() {
  scrot -z "$1"
  convert "$1" -scale 10% -scale 1000% "$1"
}

image() {
  _default_image "$1"
  echo "$1"
}

#get the image: default or user defined
if [[ -r "$IMAGE_SOURCE_SCRIPT" ]]; then
  source "$IMAGE_SOURCE_SCRIPT"
fi

# if the same path is returned, assume the image is OK
_OM="$( image "$OUTPUT_IMAGE" )"
if [[ "$OUTPUT_IMAGE" != "$_OM" ]]; then
  # otherwise convert it to the right location
  # maybe there is a format change to perform (via extension)
  convert "$_OM" "$OUTPUT_IMAGE"
fi

#Get dimensions of the lock image:
LOCK_IMAGE_INFO="$(identify "$LOCK")"
[[ "$LOCK_IMAGE_INFO" =~ $IMAGE_RE ]]
IMAGE_WIDTH="${BASH_REMATCH[1]}"
IMAGE_HEIGHT="${BASH_REMATCH[2]}"

if [[ $DISPLAY_TEXT ]] ; then
  #Get dimensions of the text image:
  TEXT_IMAGE_INFO="$(identify $TEXT)"
  [[ "$TEXT_IMAGE_INFO" =~ $IMAGE_RE ]]
  TEXT_WIDTH="${BASH_REMATCH[1]}"
  TEXT_HEIGHT="${BASH_REMATCH[2]}"
fi

#Execute xrandr to get information about the monitors:
while read -r LINE; do
  #If we are reading the line that contains the position information:
  if [[ "$LINE" =~ $DISPLAY_RE ]]; then
    #Extract information and append some parameters to the ones that will be given to ImageMagick:
    WIDTH="${BASH_REMATCH[1]}"
    HEIGHT="${BASH_REMATCH[2]}"
    X="${BASH_REMATCH[3]}"
    Y="${BASH_REMATCH[4]}"
    POS_X=$(($X+$WIDTH/2-$IMAGE_WIDTH/2))
    POS_Y=$(($Y+$HEIGHT/2-$IMAGE_HEIGHT/2))

    PARAMS="$PARAMS $LOCK -geometry +$POS_X+$POS_Y -composite"

    if [[ $DISPLAY_TEXT ]] ; then
        TEXT_X=$(($X+$WIDTH/2-$TEXT_WIDTH/2))
        TEXT_Y=$(($Y+$HEIGHT/2-$TEXT_HEIGHT/2+200))
        PARAMS="$PARAMS $TEXT -geometry +$TEXT_X+$TEXT_Y -composite"
    fi
  fi
done <<<"$(xrandr)"

# put the lock and text in the image
convert "$OUTPUT_IMAGE" $PARAMS "$OUTPUT_IMAGE"

# lock the screen
i3lock -i "$OUTPUT_IMAGE" -t

# remove the generated image
rm "$OUTPUT_IMAGE" >/dev/null 2>&1
