#!/usr/bin/sh
#
# Alejandro Villegas López (r2dedios)
#

# Run parameters
ICON=""
ITERATIONS=5 # number of "top" command iterations
DELAY=0.05   # Seconds between top iterations

# Intervals in percentage
ERR_LIMIT=${ERR_LIMIT:=90}
WARN_LIMIT=${WARN_LIMIT:=70}

# Colors
OK_COLOR="#1FC40D"
WARN_COLOR="#FFA600"
ERR_COLOR="#DE1212"

# Get CPU current usage
cpu=$(top -d $DELAY -bn$ITERATIONS |
  grep "Cpu(s)" |
  sed "s/.*, *\([0-9.]*\)%* id.*/\1/" |
  awk '
    BEGIN {
      n=0
      sum=0
    }

    {
      n+=1
      sum+=(100-$1)
    }

    END {
     print sum/n""
    }
  '
)

# Printing
if echo "$cpu > $ERR_LIMIT" | bc -l | grep -q 1; then
  COLOR="bgcolor=\"$ERR_COLOR\""
elif echo "$cpu > $WARN_LIMIT" | bc -l | grep -q 1; then
  COLOR="color=\"$WARN_COLOR\""
else
  COLOR="color=\"$OK_COLOR\""
fi

OUTPUT="<span $COLOR font='FontAwesome'>$ICON  </span><span $COLOR>$cpu%</span>"
echo "$OUTPUT"
