#!/usr/bin/sh
#
# Adormidera Organization
################################################################################

# Sourcing init vars
ARF_SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
source $ARF_SCRIPT_DIR/init.vars


# Icon
ARF_ICON="${ARF_ICON:=}"


# RUN
ARF_DIR="${ARF_DIR:=/}"

awk \
  -v arf_icon=$ARF_ICON \
  -v arf_dir=$ARF_DIR \
  -v arf_warn_limit=$ARF_WARN_LIMIT \
  -v arf_err_limit=$ARF_ERR_LIMIT \
  -v arf_ok_color=$ARF_OK_COLOR \
  -v arf_warn_color=$ARF_WARN_COLOR \
  -v arf_err_color=$ARF_ERR_COLOR \
  -v block_button=$BLOCK_BUTTON \
  -v arf_left_click=$ARF_LEFT_CLICK \
'
/\/.*/ {
  # Removing "%" to compare values
  pct=$5
  gsub(/%$/,"",pct)

  # Convert to Int
  pct=pct+0

  # Checking thresholds
  if (pct > arf_err_limit) {
    color=arf_err_color
  } else if (pct > arf_warn_limit) {
    color=arf_warn_color
  } else {
    color=arf_ok_color
  }

  # Printing
  if (block_button == arf_left_click) {
    printf("<span color=\"%s\">%s Mount: %s - %.1fG/%.1fG (%.f%%)</span>\n",
    color, arf_icon, arf_dir, $3, $2, pct)
  }

  printf("<span color=\"%s\">%s %.f%%</span>\n", color, arf_icon, $5)
}
' <<< $(df -h -P -l "$ARF_DIR")
